### PR TITLE
[WIP] Add rpm and deb support

### LINKED ISSUE #25: add debian/rpm support
By using the sbt-native-packager,we could package it as a service,I think that would be great to use.
btw,is there anychange to extract the download provider,like using `axel` or `aria2c` to download the aritifcaty?

thanks.

### PR DESCRIPTION
**Pull request by jilen**
Fix #25 
This is a working in progress pr. Needs test and review

### CODE REVIEW

**Comment by jilen** [comment]
[deb](https://www.jianguoyun.com/p/DSeyekkQwr7zBRizkBI)
[rpm](https://www.jianguoyun.com/p/DRE3jnoQwr7zBRi2kBI)

@Centaur 
> curl 'localhost:8078'

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script language="javascript">
        window.location.href = "http://centaur.github.io/repox/"
    </script>
</head>
<body>
    如果浏览器没有自动跳转, 请点击 <a href="http://centaur.github.io/repox/">这里</a>
</body>
</html>
```
Is the expected ?

**Comment by Centaur** [comment]
@jilen Yes. It is expected. I think there is no point allowing content listing since repox is a proxy-cache not a mirror. And the redirect target link has a few information that I think new comers should know.

**Comment by jilen** [comment]
@Centaur Both rpm and deb are tested. Note  debian package requires `systemd` instead of legacy `sysv`

**Comment by Centaur** [comment]
:heart: :+1: :exclamation:

**Pull request closed without merging**
